### ISSUE TITLE
LOGIN and PLAIN always returns auth failure if "allow any creds" is off

### ISSUE THREAD

**Issue by typenoob** [rnwood/smtp4dev#1515]
![image](https://github.com/rnwood/smtp4dev/assets/61347081/2bd8bcda-c8d1-4b27-a50e-1d22ba7b2c2d)
![image](https://github.com/rnwood/smtp4dev/assets/61347081/50c3a59b-6cc2-4a27-bcce-4ec1ed8a4b89)
![image](https://github.com/rnwood/smtp4dev/assets/61347081/b57967fe-1568-4949-b255-fe88ff2803bd)

![image](https://github.com/rnwood/smtp4dev/assets/61347081/fa1e026a-c997-44fb-b4d3-8dcb4aefb692)

![image](https://github.com/rnwood/smtp4dev/assets/61347081/1522415f-80fd-476c-950f-a11a5acda942)

**Comment by rnwood** [comment]
Please can you grab the session log from SMTP4dev UI.

________________________________
From: typenoob ***@***.***>
Sent: Thursday, June 6, 2024 3:53:24 AM
To: rnwood/smtp4dev ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rnwood/smtp4dev] login auth not properly verify? (Issue #1515)


image.png (view on web)<https://github.com/rnwood/smtp4dev/assets/61347081/2bd8bcda-c8d1-4b27-a50e-1d22ba7b2c2d>
image.png (view on web)<https://github.com/rnwood/smtp4dev/assets/61347081/50c3a59b-6cc2-4a27-bcce-4ec1ed8a4b89>
image.png (view on web)<https://github.com/rnwood/smtp4dev/assets/61347081/b57967fe-1568-4949-b255-fe88ff2803bd>

image.png (view on web)<https://github.com/rnwood/smtp4dev/assets/61347081/fa1e026a-c997-44fb-b4d3-8dcb4aefb692>

image.png (view on web)<https://github.com/rnwood/smtp4dev/assets/61347081/1522415f-80fd-476c-950f-a11a5acda942>

**Comment by danrollason-dd** [comment]
Hi.  Just encountered the same issue sending an email from a go app.  Our session log is

```
220 localhost smtp4dev ready
EHLO localhost
250-Nice to meet you.
250-8BITMIME
250-SIZE
250-SMTPUTF8
250-AUTH=CRAM-MD5 PLAIN LOGIN
250 AUTH CRAM-MD5 PLAIN LOGIN
AUTH PLAIN AG15c210cHVzZXIAbXlzbXRwcGFzc3dvcmQ=
535 Authentication failure
*
500 Command unrecognised
QUIT
221 Goodbye
```

Our log from the container is 

```
Session started. Client address ::ffff:127.0.0.1.
SMTP auth failure: Cannot validate credentials of type USERNAME_PASSWORD
SMTP auth failure: Cannot validate credentials of type USERNAME_PASSWORD
Session completed. Client address ::ffff:127.0.0.1. Number of messages 0.
```

**Comment by AlexGeller** [comment]
The smtp server also don't support login mechanism verification.
![A( $UW 2IN4{U3HV2}Z$4F](https://github.com/rnwood/smtp4dev/assets/5525760/139942b6-6035-4a5f-b778-4539a0d7d65b)

![LMVDG7}P86G4GZPZ5%NM71S](https://github.com/rnwood/smtp4dev/assets/5525760/4b8400ae-8334-4e7c-b45f-4fa820921490)

**Comment by rnwood** [comment]
Thanks for reporting this issue. Indeed the credential validation is only working for `CRAMMD5` mechanism here.

**Comment by rnwood** [comment]
I believe this is now resolved.

**Comment by dagnelies** [comment]
Hi there, it would be nice to leave this issue open until PLAIN/LOGIN authentication is supported ...hopefully. I was endlessly debugging why my client side was broken, but it turns out it was smtp4dev this time! 😅

**Comment by dagnelies** [comment]
Hmm... I thought it was not resolved, but looking at the date of the fix, it's probably that the docker image I pulled (rnwood/smtp4dev) doesn't yet contain the fix. It has version 3.6.1 according to the UI ...which is not listed in your releases versions ...it is weird.

**Comment by dagnelies** [comment]
Indeed, pulling the latest `rnwood/smtp4dev:prerelease` instead of `rnwood/smtp4dev` works! 🎉 

BTW, thanks for this nice piece of software.
