### ISSUE TITLE
Certificate verification error when connecting from Go

### ISSUE THREAD

**Issue by muety** [rnwood/smtp4dev#1610]
When attempting to send mail from a Go application via an smtp4dev instance that runs with a self-signed certificate, I'm getting the following error: 

```
tls: failed to verify certificate: x509: certificate relies on legacy Common Name field, use SANs instead
```

There used to be a flag that you could set to instruct Go to ignore this error (see [here](https://stackoverflow.com/a/64853881/3112139)), but apparently it has been removed after Go 1.17.

Minimal code example:

```go
package main

import (
	"fmt"
	"net/smtp"
	"os"
)

func main() {
	auth := smtp.PlainAuth("", "admin", "admin", "localhost.localdomain")
	err := smtp.SendMail("localhost.localdomain:2525", auth, "admin@example.org", []string{ "user@example.org" }, []byte("Just a test"))
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
```

**Comment by muety** [comment]
Would love to get this fixed! It's pretty much a deal breaker for me right now.

@rnwood Is the project still being maintained? I see only very few commits recently and a lot of open PRs 🤔

**Comment by rnwood** [comment]
Yes this project still has some maintenance, but only as my interest comes and goes. There is some automation to reduce the effort that is used on the important job of keeping dependencies up to date, and that's mostly what you've seen in the pending PRs.

PRs and other community involvement is welcome.

For this issue, I will investigate it shortly as looks like the common practice with certs has moved on. Go is ahead of the curve on enforcing it, but likely other will or do.

________________________________

**Comment by rnwood** [comment]
This issue should be resolved in the latest pre release builds. Please let me know if this is not the case with your use case.

Thanks
Rob

**Comment by muety** [comment]
Wow, thanks a lot for fixing this! Seems to first at first glance. I'm still getting a certificate validation error due to using a self-signed cert:

```
tls: failed to verify certificate: x509: certificate signed by unknown authority
```

But I presume that can be worked around by configuring the client to trust it anyway (specifically for Go, see [here](https://groups.google.com/g/golang-nuts/c/W95PXq99uns?pli=1)).
